/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Edu;

import java.util.Arrays;

public class App {
    public static void main(String[] args) {
        int[] arr1 = new int[]{1, 7, 2, 19, 12, 6, 21};

        QuickSort.quickSort(arr1, 0, arr1.length - 1);
        System.out.println(Arrays.toString(arr1));

    }

}
