/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Edu;

public class App {
    public static void main(String[] args) {
        // I D K why i cant import this class into this package (V) (V)
        //SortingAlgoTest.runTests();
    }
}
